theme: jekyll-theme-minimal
title: Nicole's cool homepage
description: This is the official merchandise webpage for the Squish Squad! Check out the merch, participate in the weekly challenge, and earn points toward discounts and deals!